### ISSUE TITLE
No fields yet

### ISSUE THREAD

**Issue by MaluNoPeleke** [genxbe/kirby3-instagram#2]
I have just installed and followed your plugin instructions but in the blueprint field I see only the message "No fields yet".
I am using Kirby 3.6.0 alpha. Could that be the problem?

**Comment by MaluNoPeleke** [comment]
Mistake by me, works with 3.6.0

**Comment by samzzi** [comment]
Just tested and it indeed works on 3.6 alpha4. Thx for closing though :)

Just for reference, here is the blueprint I used for testing:

```yaml
title: Site
preset: pages
unlisted: true

fields:
  linkInstagram: linkInstagram
```
![CleanShot 2021-08-17 at 21 48 17](https://user-images.githubusercontent.com/32242279/129791437-0a27e795-3e90-4864-b910-7df2a13f55d4.jpg)
